name: Daily News Scraper

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:

  scrape:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4 python-dotenv supabase
    - name: Scrape articles
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }} 
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python SCRAPPER/fetch_articles.py
        python SCRAPPER/Standard_news.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "Daily scrape" && git push)

      name: Clean Up
      run: |
      python SCRAPPER/delete_old_records.py
