name: Scrape

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *' # Runs every 1/2 hour

jobs:

  commit-articles:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4 dateutil

    - name: Run script to fetch and commit articles
      env:
        GITHUB_TOKEN: ${{ secrets.PAT}}
      run: |
        python your_script.py
        git config --global user.email "ndungusamkelly5@gmail.com"
        git config --global user.name "Icey-Python"
        git add articles.json
        git commit -m "Articles updated at $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
